#include "stm32f10x.h"
#include "gpio.h"

void exti_gpio_init(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;
	
	GPIOA->CRL &= ~EXTI_GPIO_MASK;
	GPIOA->CRL |= ((GPIO_IN << GPIO0_MODE*4) | ( GPIO_IN_PU_PD << (GPIO0_MODE*4)));
	AFIO->EXTICR[0] &= ~AFIO_EXTICR1_EXTI0;
	AFIO->EXTICR[0] |= AFIO_EXTICR1_EXTI0_PA;
	
	EXTI->IMR |= EXTI_IMR_MR0;
	EXTI->FTSR |= EXTI_FTSR_TR0;
	
	NVIC_SetPriority(EXTI0_IRQn, EXTI0_PRIOR);
	NVIC_EnableIRQ(EXTI0_IRQn);
	
	
}
